In [400]:
import numpy as np

def f(x):
    a = 1.1
    b = 2
    return int(a*x+b)

def generator(start):
    n = 10
    a = start
    niz = []
    for i in range(n):
        niz.append(a)
        a = f(a)
    return niz

niz = generator(2)
print(niz)

[2, 4, 6, 8, 10, 13, 16, 19, 22, 26]


In [401]:
xs = np.array(niz[:-1], dtype=np.float32)
ys = np.array(niz[1:], dtype=np.float32)

print(xs, ys)

[ 2.  4.  6.  8. 10. 13. 16. 19. 22.] [ 4.  6.  8. 10. 13. 16. 19. 22. 26.]


In [403]:
def prvi_metod(xs, ys):
    n = xs.shape[0]
    a = 0.5
    b = 0.5
    a_best = a
    b_best = b
    err = -1
    def greska(xs, ys):
        s = 0
        for i in range(n):
            yp = int(a*xs[i]+b)
            y = ys[i]
            s += np.abs(yp-y)
        return s
        
    for it in range(1000):
        a = 3*np.random.random(1)
        b = 3*np.random.random(1)
        e = greska(xs, ys)
        if err==-1 or e<err:
            a_best = a
            b_best = b
            err = e
            if err == 0:
                break

    a = a_best
    b = b_best
    x = ys[-1]

    print(f'Err: {err}')
    sledeci_u_nizu = int(a*x+b)
    print(f'Sledeci u nizu: {sledeci_u_nizu}')

prvi_metod(xs, ys)

Err: 1.0
Sledeci u nizu: 30


In [404]:

def drugi_metod(xs, ys, x):
    n = len(xs)

    aa = []
    bb = []

    for it in range(50):
        i = np.random.randint(0, n)
        j = np.random.randint(0, n)
        if i != j:
            xi = xs[i]
            yi = ys[i]
            xj = xs[j]
            yj = ys[j]
            dx = xj-xi
            dy = yj-yi
            a = dy/dx
            b = yi-a*xi
            aa.append(a)
            bb.append(b)
    aa = np.array(aa)
    bb = np.array(bb)

    a = aa.mean()
    b = bb.mean()
    print(f'a={a} b={b}')
    return int(a*x+b)

x =niz[-1]
y = drugi_metod(xs, ys, x)
yt = f(x)
print(f'Ako je x={x} y={y} tacna vrednost={yt}')

a=1.1229777336120605 b=1.1180272102355957
Ako je x=26 y=30 tacna vrednost=30


In [378]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
# tf.keras.utils.set_random_seed(42)

xst = tf.convert_to_tensor(np.array([(x,) for x in xs]))
yst = tf.convert_to_tensor(np.array([(y,) for y in ys]))

# model = tf.keras.models.Sequential([
#   tf.keras.layers.Dense(10, activation='linear', name="layer1", input_shape=(1,)),
#   tf.keras.layers.Dense(10, activation='relu', name="layer2"),
#   tf.keras.layers.Dense(10, activation='relu', name="layer3"),
#   tf.keras.layers.Dense(1, activation='relu', name="layer4"),
# ])
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(15, input_dim=1, kernel_initializer='he_normal', activation='relu'))
# model.add(tf.keras.layers.Dropout(0.2))
# model.add(tf.keras.layers.Dense(15, kernel_initializer='he_normal', activation='relu'))
# model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(1, kernel_initializer='he_normal', activation='linear'))

loss_fn = tf.keras.losses.MeanSquaredError()

model.compile(optimizer='adam', loss='mse', metrics=['mse'])
model.build()
model.summary()
model.fit(xst, yst, epochs=1000, batch_size=1)

# # x = tf.convert_to_tensor(niz[-1])



TensorFlow version: 2.15.0
Model: "sequential_244"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_442 (Dense)           (None, 15)                30        
                                                                 
 dense_443 (Dense)           (None, 1)                 16        
                                                                 
Total params: 46 (184.00 Byte)
Trainable params: 46 (184.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Epoch 1/1000
9/9 [==============================] - 0s 710us/step - loss: 173.8975 - mse: 173.8975
Epoch 2/1000
9/9 [==============================] - 0s 657us/step - loss: 144.8414 - mse: 144.8414
Epoch 3/1000
9/9 [==============================] - 0s 723us/step - loss: 120.2625 - mse: 120.2625
Epoch 4/1000
9/9 [==============================] - 0s 681us/step - loss: 97.9511 - mse: 97.9511
Epoch 5/1000
9/9 [==============================] - 0s 737us/step - loss: 80.0750 - mse: 80.0750
Epoch 6/1000
9/9 [==============================] - 0s 651us/step - loss: 63.2885 - mse: 63.2885
Epoch 7/1000
9/9 [==============================] - 0s 637us/step - loss: 49.9557 - mse: 49.9557
Epoch 8/1000
9/9 [==============================] - 0s 656us/step - loss: 39.1782 - mse: 39.1782
Epoch 9/1000
9/9 [==============================] - 0s 631us/step - loss: 30.9420 - mse: 30.9420
Epoch 10/1000
9/9 [==============================] - 0s 752us/step - loss: 23.6129 - mse: 23.6129
Epoch 11/1000
9/9 [====

In [379]:
y = model(xst)
print(y)
print(yst)

tf.Tensor(
[[ 4.7617054]
 [ 8.0474615]
 [11.333217 ]
 [14.61897  ]
 [18.999979 ]
 [23.380987 ]
 [27.761993 ]
 [33.238255 ]
 [38.71451  ]], shape=(9, 1), dtype=float32)
tf.Tensor(
[[ 5.]
 [ 8.]
 [11.]
 [15.]
 [19.]
 [23.]
 [28.]
 [33.]
 [39.]], shape=(9, 1), dtype=float32)
